# Site settings
title: Caffetteria Porto di Mare
title_image: "/img/logo-min.jpg"
meta_description:
  it: Situato nel cuore del centro storico, nei pressi del Castello Svevo e a due passi dalla cattedrale, la Caffetteria Porto di Mare è il luogo ideale per rilassarsi e gustare un ottimo caffè.
  en: Situated in the heart of the historical centre, near Castello Svevo and a few steps away from the Cathedral, the Caffetteria Porto di Mare is the ideal place to relax and enjoy a delicious coffee.
description:
  en: >
      Situated in the heart of the historical centre, near Castello Svevo and a few steps away from the Cathedral, the Caffetteria Porto di Mare is the ideal place to relax and enjoy a delicious coffee.
      <br>Join us and taste our aperitivi and pastries inspired local seasonal flavours.
  it: >
      Situato nel cuore del centro storico, nei pressi del Castello Svevo e a due passi dalla cattedrale, la Caffetteria Porto di Mare è il luogo ideale per rilassarsi e gustare un ottimo caffè.
      <br>Vieni a trovarci e assapora i nostri aperitivi e dolci ispirati dai sapori locali e di stagione.
galleryh1:
  en: Gallery
  it: Galleria
index:
  it: /
  en: /index_en.html
images:
  it: /images
  en: /images_en.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://portodimare.bar" # the base hostname & protocol for your site
twitter_username: portodimarebar
instagram_username: portodimarebar
#pinterest_username: portodimarebar
facebook_username: portodimarebar
google_maps_location: 41.2814733,16.4162785,19z
google_analytics: "UA-77507999-1"

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
