# Site settings
title: Porto Di Mare
title_image: "/img/logo-min.jpg"
email: your-email@domain.com
meta_description:
  it: italiano
  en: english
description:
  en: Write an awesome description for your new site in english here.
  it: Write an awesome description for your new site in italian here.
galleryh1:
  en: Gallery
  it: Galleria
index:
  it: /
  en: /index_en.html
images:
  it: /images
  en: /images_en.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://portodimare.bar" # the base hostname & protocol for your site
twitter_username: portodimarebar
instagram_username: portodimarebar
pinterest_username: portodimarebar
facebook_username: portodimarebar
google_maps_location: 41.2814733,16.4162785,19z
google_analytics: "NOT_SET_YET"

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
